spring:
  application:
    name: fast-food-api
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/fastfood?currentSchema=public
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    database: Postgresql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  flyway:
    schemas: public
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/fastfood?currentSchema=public
    user: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

cors:
  url: http://localhost:3000

logging:
  level:
    root: INFO 

