apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pod-fast-food-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pod-fast-food-api
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50