apiVersion: v1
kind: Service
metadata:
  name: svc-fast-food-api
spec:
  selector:
    app: pod-fast-food-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort